version: "2"
services:
  salas_miner:
    build: 
      context: .
      args:
        gethrepo: $GETH_REPO
    ports:
      - "8545:8545"
      - "31313:31313"
    entrypoint: /bin/bash -c
    volumes:
      - ./vol_keystore:/salas/miner/keystore
      - ./vol_conf:/salas/miner/conf
      - ./vol_data:/salas/miner/ethereum_data
      - ./vol_faucet_session:/salas/faucet/session
    command: >
      "(pcscd) 
      && (cd /salas/miner/ && ./1_clean_miner.sh && ./2_init_miner_address.sh && ./2_init_miner_genesis.sh)
      && (cd /salas/miner/ && ./3_start_miner.sh &) 
      && (sleep 5)
      && (cd /salas/faucet/ && python3 ./4_serve_faucet.py &)
      && (sleep 5)
      && (cd /salas/miner/ && python3 ./5_start_salas_mining.py)"
    env_file:
      - .env.cmds
      - .env.secrets
      - .env
    stdin_open: true
    tty: true      
    privileged: true # needed for the smartcard, but a little to insecure maybe (better per device)
