version: "2"
services:
  salas_miner:
    build: 
      context: .
      args:
        gethrepo: $GETH_REPO
    ports:
      - "8545:8545"
      - "31313:31313"
    entrypoint: /bin/bash -c
    volumes:
      - ./vol_keystore:/salas/miner/keystore
      - ./vol_conf:/salas/miner/conf
      - ./vol_data:/salas/miner/ethereum_data
      - ./vol_faucet_session:/salas/faucet/session
    command: >
      "(pcscd) 
      && (echo '********* CLEANING AND INITIALIZATION STEPS (starts in 5 secs) ********')
      && (sleep 1)
      && (cd /salas/miner/ && ./1_clean_miner.sh && ./2_init_miner_address.sh && ./2_init_miner_genesis.sh)
      && (echo '********* STARTING NODE (starts in 5 secs) ********')
      && (sleep 1)
      && (cd /salas/miner/ && ./3_start_miner.sh &) 
      && (echo '********* STARTING FAUCET IF REQUESTED (starts in 5 secs) ********')
      && (sleep 1)
      && (cd /salas/faucet/ && python3 ./4_serve_faucet.py &)
      && (echo '********* STARTING MINING WITH EID (starts in 5 secs) ********')
      && (sleep 1)
      && (cd /salas/miner/ && python3 ./5_start_salas_mining.py &)
      && (echo '********* CONTRACT DEPLOYMENT IF REQUESTED (starts in 5 secs) ********')
      && (sleep 1)
      && (cd /salas/salas_contract/ && python3 ./1_compile_and_deploy_salas_contract.py)
      && (sleep infinity)"
    env_file:
      - .env.user
      - .env.secrets
      - .env
    stdin_open: true
    tty: true      
    privileged: true # needed for the smartcard, but insecure (better use devices)
